using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Intex.Models;
using Intex.Components;
using Intex.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

public class AdminController : Controller
{
    
    private readonly ILogger<AdminController> _logger;
    private readonly ILegoRepository _repo;
    public List<SelectListItem> Genders { get; set; }

    public AdminController(ILogger<AdminController> logger, ILegoRepository repo)
    {
        _logger = logger;
        _repo = repo;
    }
    
    public IActionResult Index()
    {
        Genders = new List<SelectListItem>
        {
            new SelectListItem("Male", "M"),
            new SelectListItem("Female", "F"),
        };
        
        var usersWithCustomersAndRoles = _repo.Users
            .Join(
                _repo.Customers,
                user => user.user_id, // Assuming 'user_id' is your join key in 'User'
                customer => customer.customer_ID, // Assuming 'UserId' is your join key in 'Customer'
                (user, customer) => new UsersViewModel
                {
                    User = user,
                    Customer = customer
                }
            )
            .ToList();


        // Materialize the first query
        /*var usersWithCustomers = _repo.Users
            .Join(
                _repo.Customers,
                user => user.user_id, // Assuming 'user_id' is your join key in 'Users'
                customer => customer.customer_ID, // Assuming 'customer_ID' is your join key in 'Customers'
                (user, customer) => new { User = user, Customer = customer }
            )
            .Join(_repo.AspNetUsers,
                u => u.User.username,
                un => un.UserName,
                (uc, aspNetUser) => new { uc.User, uc.Customer, AspNetUser = aspNetUser }
                )
            .Join(
                _repo.AspNetUserRoles, // Assuming this is the name of your UserRoles repo
                uc => uc.User.user_id, // User Id from the previous join
                userRole => userRole.UserId, // Assuming 'UserId' is the name in UserRoles
                (uc, userRole) => new { uc.User, uc.Customer, userRole.RoleId }
            )
            .Join(
                _repo.AspNetRoles, // Assuming this is the name of your Roles repo
                ucr => ucr.RoleId, // Role Id from previous join
                role => role.Id, // Assuming 'Id' is the name of the role identifier in AspNetRoles
                (ucr, role) => new UsersViewModel
                {
                    User = ucr.User,
                    Customer = ucr.Customer,
                    Role = role.Name // Or whatever property holds the role name
                }
            )
            .Take(10)
            .ToList();*/

        // Assign the materialized data to ViewBag
        ViewBag.Genders = Genders;
        return View(usersWithCustomersAndRoles);
    }

    public IActionResult ManageItems()
    {
        var products = _repo.Products
            .Select(p => new ItemViewModel
            {
                ProductId = p.product_id,
                ProductName = p.name,
                Year = p.year,
                NumberOfParts = p.num_parts,
                Price = p.price
            })
            .ToList();

        return View(products);
    }


    [HttpGet]
    public IActionResult AddProduct()
    {
        // Create a new instance of the AddProductViewModel
        var model = new AddProductViewModel();

        // Attempt to fetch categories from the repository
        var categories = _repo.Categories?.ToList();

        // Check if the categories list is null or empty
        if (categories == null || !categories.Any())
        {
            // Handle the scenario where there are no categories
            // You could log this situation because it's unexpected based on your application's requirements
            _logger.LogWarning("Categories list is null or empty when accessing AddProduct view.");

            // Initialize an empty SelectList to prevent null reference in the view
            ViewBag.Categories = new SelectList(Enumerable.Empty<SelectListItem>());
        }
        else
        {
            // Successfully retrieved categories, pass them to the view via ViewBag
            ViewBag.Categories = new SelectList(categories, "CategoryId", "CategoryName");
        }

        // Pass the model to the view
        return View(model);
    }


    [HttpPost]
    public IActionResult AddProduct(AddProductViewModel model)
    {
        if (ModelState.IsValid)
        {
            // Map the ViewModel to your database model
            var product = new Product
            {
                // Assuming 'product_id' is auto-generated by the database, so it's not set here

                name = model.Name, // Make sure the property names match your Product model and ViewModel
                year = model.Year,
                num_parts = model.NumParts,
                price = model.Price,
                img_link = model.ImgLink,
                primary_color = model.PrimaryColor,
                secondary_color = model.SecondaryColor,
                description = model.Description,
                category_id = model.CategoryId
                // 'DescriptionShort' is not included as it's not part of your Product model
            };

            // Add and save in the database
            //_repo.AddProduct(product); // Ensure your repository's AddProduct method is expecting a Product entity
            //_repo.SaveChanges(); // Save the changes

            // Redirect to the ManageItems view to see the list of products
            return RedirectToAction("ManageItems");
        }

        // If the model state is not valid, return to the AddProduct view with the current model to show validation errors
        // Repopulate necessary data like categories
        ViewBag.Categories = new SelectList(_repo.Categories, "CategoryId", "CategoryName");
        return View(model);
    }



}